export const socialPostsData = [
  {
    id: 1,
    author: 'Gaming Pro User',
    avatar: 'https://i.pravatar.cc/150?img=1',
    image: 'https://picsum.photos/id/60/400/300',
    content: 'Just completed the new level! Amazing graphics and gameplay!',
    likes: 342,
    comments: 45,
    timestamp: '2 hours ago',
  },
  {
    id: 2,
    author: 'Community Manager',
    avatar: 'https://i.pravatar.cc/150?img=2',
    image: 'https://picsum.photos/id/61/400/300',
    content: 'Exciting announcement: New game update coming next week!',
    likes: 521,
    comments: 87,
    timestamp: '4 hours ago',
  },
  {
    id: 3,
    author: 'Content Creator',
    avatar: 'https://i.pravatar.cc/150?img=3',
    image: 'https://picsum.photos/id/62/400/300',
    content: 'Check out my latest stream highlight reel - didn\'t miss a single achievement!',
    likes: 1203,
    comments: 156,
    timestamp: '6 hours ago',
  },
  {
    id: 4,
    author: 'Game Developer',
    avatar: 'https://i.pravatar.cc/150?img=4',
    image: 'https://picsum.photos/id/63/400/300',
    content: 'Behind the scenes: Creating the future of gaming',
    likes: 892,
    comments: 124,
    timestamp: '8 hours ago',
  },
]
